console:
  image:
    version: 1.6.2.1
console-api:
  image:
    version: 1.6.2.1
identity:
  image:
    version: 1.6.4-rc3
    repository: pyengine
secret:
  image:
    version: 1.6.4-rc2
    repository: pyengine
repository:
  image:
    version: 1.6.4-rc2
    repository: pyengine
plugin:
  image:
    version: 1.6.4-rc2
    repository: spaceone
config:
  image:
    version: 1.6.4-rc1.20210301.003405
    repository: pyengine
inventory:
  image:
    version: 1.6.4-rc1.20210301.004600
    repository: pyengine
monitoring:
  image:
    version: 1.6.4-rc1.20210301.004835
    repository: pyengine
statistics:
  image:
    version: 1.6.4-rc1.20210301.005134
    repository: pyengine
billing:
  image:
    version: 1.6.4-rc1.20210301.005341
    repository: pyengine
power-scheduler:
  image:
    version: 1.6.2
supervisor:
  image:
    version: 1.6.4
